export const LOAD_FOLLOWERS_SUCCESS = 'LOAD_FOLLOWERS_SUCCESS';
export const UPDATE_FOLLOWERS_SUCCESS = 'UPDATE_FOLLOWERS_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const ADD_USER_TO_FAVORITES_SUCCESS = 'ADD_USER_TO_FAVORITES_SUCCESS';
export const CREATE_APP_USER = 'CREATE_APP_USER';
export const RESET = 'RESET';
